---
- name: Get Oracle MySQL GPG key
  get_url:
    url: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
    dest: /tmp/RPM-GPG-KEY-mysql-2023
  when: ansible_distribution == 'Ubuntu'

- name: Import Oracle MySQL GPG key
  become: true
  command: |
    gpg --batch --yes --dearmor -o /usr/share/keyrings/mysql-apt-config.gpg /tmp/RPM-GPG-KEY-mysql-2023
  when: ansible_distribution == 'Ubuntu'
  args:
    creates: /usr/share/keyrings/mysql-apt-config.gpg

- name: Adding the Oracle MySQL APT Repository for Ubuntu 24.04
  become: true
  copy:
    dest: /etc/apt/sources.list.d/mysql.list
    content: |
      deb [signed-by=/usr/share/keyrings/mysql-apt-config.gpg] https://repo.mysql.com/apt/ubuntu/ noble mysql-8.4-lts
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

- name: Update APT package index
  become: true
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Configure MySQL root password
  become: true
  shell: |
    PASSWORD=$(openssl rand -base64 12)
    echo -n $PASSWORD > /root/mysql-root-password.txt
    echo "mysql-community-server mysql-community-server/root-pass password $PASSWORD" | debconf-set-selections
    echo "mysql-community-server mysql-community-server/re-root-pass password $PASSWORD" | debconf-set-selections
    apt-get install -y mysql-community-server
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Start MySQL Server
  become: true
  service:
    name: mysql
    state: started
    enabled: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Read MySQL log file
  become: true
  slurp:
    src: /var/log/mysql/error.log
  register: mysql_log

- name: Display MySQL log file
  debug:
    msg: "File content is: {{ mysql_log.content | b64decode }}"

- name: Install MySQL Client
  become: true
  apt:
    name: mysql-community-client
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Configure MySQL for current user
  become: true
  copy:
    dest: "{{ ansible_env.HOME }}/.my.cnf"
    content: |
      [client]
      host     = 127.0.0.1
      user     = root
      password = "{{ lookup('file', '/root/mysql-root-password.txt') }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

- name: Debug output for user MySQL configuration location
  become: true
  debug:
    msg: "{{ ansible_env.HOME }}/.my.cnf"

- name: Ream MySQL configuration file
  become: true
  slurp:
    src: "{{ ansible_env.HOME }}/.my.cnf"
  register: mysql_cnf

- name: Display MySQL configuration file
  debug:
    msg: "File content is: {{ mysql_cnf.content | b64decode }}"
