---
- name: Get Oracle MySQL GPG key
  get_url:
    url: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
    dest: /tmp/RPM-GPG-KEY-mysql-2023
  when: ansible_distribution == 'Ubuntu'

- name: Import Oracle MySQL GPG key
  command: |
    gpg --batch --yes --dearmor -o /usr/share/keyrings/mysql-apt-config.gpg /tmp/RPM-GPG-KEY-mysql-2023
  when: ansible_distribution == 'Ubuntu'
  args:
    creates: /usr/share/keyrings/mysql-apt-config.gpg

- name: Adding the Oracle MySQL APT Repository for Ubuntu 24.04
  become: true
  copy:
    dest: /etc/apt/sources.list.d/mysql.list
    content: |
      deb [signed-by=/usr/share/keyrings/mysql-apt-config.gpg] https://repo.mysql.com/apt/ubuntu/ noble mysql-8.4-lts
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

- name: Update APT package index
  become: true
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Generate MySQL root password and save to file
  become: true
  shell: |
    PASSWORD=$(openssl rand -base64 12)
    echo -n $PASSWORD > /root/mysql-root-password.txt
  args:
    creates: /root/mysql-root-password.txt
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

- name: Read MySQL root password from file
  become: true
  slurp:
    src: /root/mysql-root-password.txt
  register: mysql_root_password_file
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

- name: Read MySQL root password
  become: true
  slurp:
    src: /root/mysql-root-password.txt
  register: mysql_root_password_txt

- name: Display MySQL root password
  debug:
    msg: "File content is: {{ mysql_root_password_txt.content | b64decode }}"

- name: Configure MySQL root password
  become: true
  shell: |
    PASSWORD=$(cat /root/mysql-root-password.txt)
    echo "mysql-community-server mysql-community-server/root-pass password $PASSWORD" | debconf-set-selections
    echo "mysql-community-server mysql-community-server/re-root-pass password $PASSWORD" | debconf-set-selections
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Install MySQL Server
  become: true
  apt:
    name: mysql-community-server
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Start MySQL Server
  become: true
  service:
    name: mysql
    state: started
    enabled: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Install MySQL Client
  become: true
  apt:
    name: mysql-community-client
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
  changed_when: false

- name: Debug output for user MySQL configuration location
  become: true
  debug:
    msg: "{{ ansible_env.HOME }}/.my.cnf"

- name: Configure MySQL for current user
  become: true
  copy:
    dest: "{{ ansible_env.HOME }}/.my.cnf"
    content: |
      [client]
      host     = 127.0.0.1
      user     = root
      password = "{{ mysql_root_password_file.content | b64decode}}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'
