---
- name: Test Percona Server role
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Include Percona Server role
      ansible.builtin.include_role:
        name: ../../../roles/percona_server
        tasks_from: main.yml