---
namespace: rostyslav
name: mysql
version: 1.0.22
readme: README.md
authors:
  - Rostyslav Rava
description: MySQL and Percona Server for MySQL Ansible Collection
license_file: LICENSE
tags:
  - database
  - mysql
  - percona
repository: https://github.com/rostyslav/rostyslav.mysql
documentation: https://github.com/rostyslav/rostyslav.mysql
homepage: https://github.com/rostyslav/rostyslav.mysql
issues: https://github.com/rostyslav/rostyslav.mysql/issues
build_ignore:
  - .gitignore
  - .idea
  - changelogs/.plugin-cache.yaml
  - '*.tar.gz'
  - publish.sh

