---
namespace: rostyslav
name: mysql
version: 1.0.0
readme: README.md
authors:
  - Rostyslav Rava
description: OverBase MySQL collection
license_file: LICENSE
tags:
  - database
  - mysql
repository: https://github.com/overbase/overbase.mysql
documentation: https://github.com/overbase/overbase.mysql
homepage: https://github.com/overbase/overbase.mysql
issues: https://github.com/overbase/overbase.mysql/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - '*.tar.gz'
