---
namespace: rostyslav
name: mysql
version: 1.0.7
readme: README.md
authors:
  - Rostyslav Rava
description: MySQL Ansible Collection by Rostyslav Rava
license_file: LICENSE
tags:
  - database
  - mysql
repository: https://github.com/rostyslav/rostyslav.mysql
documentation: https://github.com/rostyslav/rostyslav.mysql
homepage: https://github.com/rostyslav/rostyslav.mysql
issues: https://github.com/rostyslav/rostyslav.mysql/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - '*.tar.gz'
