---

- name: Download the percona-release repository package
  become: true
  shell: |
    cd /tmp
    curl -O https://repo.percona.com/apt/percona-release_latest.generic_all.deb
  when: supported_distributions
  args:
    creates: "/tmp/percona-release_latest.generic_all.deb"

- name: Install the downloaded package
  become: true
  shell: |
    cd /tmp
    apt -y install ./percona-release_latest.generic_all.deb
  when: supported_distributions
  changed_when: false

- name: Use percona-release to set up the repository for the Percona Server for MySQL
  become: true
  shell: |
    percona-release enable-only ps-84-lts release
    percona-release enable tools release
  when: supported_distributions
  changed_when: false

- name: Update APT package index
  become: true
  apt:
    update_cache: yes
  when: supported_distributions
  changed_when: false
