---
- name: Include MySQL Oracle role from a collection
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Testing MySQL Oracle role
      ansible.builtin.include_role:
        name: ../../../../roles/mysql_server
        tasks_from: main.yml