- name: Verify
  hosts: localhost
  tasks:

    - name: Get current user name
      ansible.builtin.command: whoami
      register: current_user

    - name: Display current user name
      ansible.builtin.debug:
        msg: "Current user is {{ current_user.stdout }}"

    - name: Initialize role MySQL Oracle without actually running it
      ansible.builtin.include_role:
        name: ../../../../roles/mysql_server
        tasks_from: init

    - name: Check if MySQL Oracle keyring exists
      stat:
        path: /usr/share/keyrings/mysql-apt-config.gpg
      register: mysql_apt_config_gpg

    - name: Assert that the MySQL Oracle keyring exists
      assert:
        that:
          - mysql_apt_config_gpg.stat.exists

    - name: Check if MySQL Oracle APT repository file exists
      stat:
        path: /etc/apt/sources.list.d/mysql.list
      register: mysql_apt_repository

    - name: Assert that the MySQL Oracle APT repository file exists
      assert:
        that:
          - mysql_apt_repository.stat.exists

    - name: Check if MySQL server is up and running
      shell: systemctl is-active mysql
      register: mysql_service

    - name: Assert that MySQL server is active
      assert:
        that:
          - mysql_service.stdout == 'active'

    - name: Connect to MySQL server and get version
      command: mysql -N -s -e "SELECT VERSION();"
      register: mysql_version

    - name: Assert that MySQL server version is 8.4.2
      assert:
        that:
          - mysql_version.stdout == '8.4.2'