- name: Verify
  hosts: localhost
  tasks:

    - name: Get current user name
      ansible.builtin.command: whoami
      register: current_user

    - name: Display current user name
      ansible.builtin.debug:
        msg: "Current user is {{ current_user.stdout }}"

    - name: Initialize role MySQL Oracle without actually running it
      ansible.builtin.include_role:
        name: ../../../../roles/mysql_oracle
        tasks_from: init

    - name: Check if MySQL Oracle GPG key exists
      stat:
        path: /tmp/RPM-GPG-KEY-mysql-2023
      register: rpm_gpg_key_mysql_2023

    - name: Assert that the MySQL Oracle GPG key exists
      assert:
        that:
          - rpm_gpg_key_mysql_2023.stat.exists
          -
    - name: Check if MySQL Oracle keyring exists
      stat:
        path: /usr/share/keyrings/mysql-apt-config.gpg
      register: mysql_apt_config_gpg

    - name: Assert that the MySQL Oracle keyring exists
      assert:
        that:
          - mysql_apt_config_gpg.stat.exists
          -
    - name: Check if MySQL Oracle APT repository file exists
      stat:
        path: /etc/apt/sources.list.d/mysql.list
      register: mysql_apt_repository

    - name: Assert that the MySQL Oracle APT repository file exists
      assert:
        that:
          - mysql_apt_repository.stat.exists

    - name: Check if MySQL root password file exists
      become: true
      stat:
        path: /root/mysql-root-password.txt
      register: mysql_root_password

    - name: Assert that the MySQL root password file exists
      assert:
        that:
          - mysql_root_password.stat.exists

    - name: Check if MySQL server is up and running
      service:
        name: mysql
      register: mysql_service

    - name: Assert that MySQL server is up and running
      assert:
        that:
          - mysql_service.state == 'started'

    - name: Read file content
      slurp:
        src: "{{ ansible_env.HOME }}/.my.cnf"
      register: my_cnf

    - name: Display file content
      debug:
        msg: "File content is: {{ my_cnf | b64decode }}"

    - name: Connect to MySQL server and get version
      command: mysql -N -s -e "SELECT VERSION();"
      register: mysql_version

    - name: Assert that MySQL server version is 8.4.2
      assert:
        that:
          - mysql_version.stdout == '8.4.2'