galaxy_info:
  author: Rostyslav Rava
  description: Role for MySQL community server installation
  license: MIT
  min_ansible_version: 2.1

  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  platforms:
    - name: Ubuntu
      versions:
        - 24.04
    - name: Debian
      versions:
        - 12

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies:
  - role: mysql_apt
    when: ansible_os_family == 'Debian'
