---
- name: Include MySQL APT role from the collection
  hosts: localhost
  gather_facts: true
  vars_files:
    - ../../../vars/main.yml
  tasks:
    - name: Testing MySQL APT role
      ansible.builtin.include_role:
        name: ../../../roles/mysql_apt
        tasks_from: main.yml