---
- name: Display Ansible distribution
  ansible.builtin.debug:
    msg: "Ansible distribution is {{ ansible_distribution }}"

- name: Display Ansible distribution version
  ansible.builtin.debug:
    msg: "Ansible distribution version is {{ ansible_distribution_version }}"

- name: Display Ansible distribution major version
  ansible.builtin.debug:
    msg: "Ansible distribution version is {{ ansible_distribution_major_version }}"

- name: Import MySQL GPG key
  become: true
  shell: |
    curl -s {{ mysql_gpg_key_url }} | gpg --batch --yes --dearmor -o {{ mysql_gpg_key_path }}
  when: supported_distributions
  args:
    creates: "{{ mysql_gpg_key_path }}"

- name: Adding the MySQL APT Repository for Ubuntu 22.04
  become: true
  copy:
    dest: /etc/apt/sources.list.d/mysql.list
    content: |
      deb [signed-by={{ mysql_gpg_key_path }}] https://repo.mysql.com/apt/ubuntu/ jammy mysql-8.4-lts
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: Adding the MySQL APT Repository for Ubuntu 24.04
  become: true
  copy:
    dest: /etc/apt/sources.list.d/mysql.list
    content: |
      deb [signed-by={{ mysql_gpg_key_path }}] https://repo.mysql.com/apt/ubuntu/ noble mysql-8.4-lts
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

- name: Adding the MySQL APT Repository for Debian 12
  become: true
  copy:
    dest: /etc/apt/sources.list.d/mysql.list
    content: |
      deb [signed-by={{ mysql_gpg_key_path }}] https://repo.mysql.com/apt/debian/ bookworm mysql-8.4-lts
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '12'

- name: Update APT package index
  become: true
  apt:
    update_cache: yes
  when: supported_distributions
  changed_when: false
