---
- name: Include MySQL Client role from the collection
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Testing MySQL Client role
      ansible.builtin.include_role:
        name: ../../../roles/mysql_client
        tasks_from: main.yml