---
- name: Include MySQL Server role from the collection
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Testing MySQL Server role
      ansible.builtin.include_role:
        name: ../../../../roles/mysql_server
        tasks_from: main.yml