name: Rostyslav MySQL CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Configure Git default branch name
      run: git config --global init.defaultBranch master

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install debconf-utils
      run: sudo apt-get install debconf-utils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install molecule ansible-lint

    - name: Check Molecule version
      run: |
        molecule --version

    - name: Run Molecule tests
      run: |
        cd extensions
        molecule test