---
- name: Test MySQL server role on Ubuntu 24.04
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include MySQL server role
      ansible.builtin.include_role:
        name: ../../roles/mysql_server
        tasks_from: main.yml